version: '3'

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - data:/usr/TODO/staticfiles/images/

  web:
    build: .
    ports:
      - "8000:8000"
    command:
      sh -c "python -c 'import time; time.sleep(45);' && python manage.py migrate && python manage.py loaddata task/fixtures/create_default_statuses.json && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  data:
